### ISSUE TITLE
Better inotify service

### ISSUE THREAD

**Issue by uiii** [linuxserver/docker-reverseproxy#6]
There are some issues with your inotify service.

1. If I edit a site config with Vim editor it won't detect change because Vim doesn't directly modify the file but creates a new one and then replace the old one. More here: https://unix.stackexchange.com/questions/188873/using-inotifywait-along-with-vim

2. It only watches changes in `config/apache/site-confs/default.conf`, what about other files like `config/http-server/apache/apache2.conf` or if new *site-conf* file is added.

I've modified the inotify `run` script to watch `modify` event on all `*.conf` files in `config/apache` directory and all subdirectories:
```sh
#!/bin/sh

/sbin/setuser abc inotifywait -m -r -e modify /config/apache --format %w%f | while read file; do
        if [ "${file##*.}" = "conf" ]; then
                sv down /etc/service/web/
                sv up /etc/service/web
                echo "$file changed, restarting"
        fi
done
```

It solves both issues.

**Comment by thelamer** [comment]
Created PR https://github.com/linuxserver/docker-apache/pull/7

**Comment by sparklyballs** [comment]
this container is scheduled to be deprecated in the very near future
